# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-24 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20180823_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='', upload_to='images/teacher/%Y/%m', verbose_name='\u56fe\u50cf'),
        ),
    ]
