# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-18 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='images/courses/%Y/%m', verbose_name='\u5c01\u9762'),
        ),
    ]
