# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-26 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='notice',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u8bfe\u7a0b\u516c\u544a'),
        ),
    ]
